<script>
  import ProjectPage from "$lib/project/ProjectPage.svelte";

  import "../../../styles/global.scss";
</script>

<ProjectPage
  title="tensort"
  category="learning_projects"
  repository={["connellr023/tensort", "https://github.com/connellr023/tensort"]}
>
  <h2 class="left-bar fade-in">overview</h2>
  <p class="left-bar fade-in">
    This project is a <b>CLI</b> tool that sorts images based on their content.
    It uses a pre-trained <b>ResNet</b> model to classify images and then sort them
    into folders based on the classification.
  </p>

  <h2 class="left-bar fade-in">note</h2>
  <p class="left-bar fade-in">
    It is worth noting that I did not train the model. The weights were obtained
    from the <b
      ><a target="_blank" href="https://github.com/LaurentMazare/tch-rs"
        >tch.rs</a
      ></b
    >
    repository which is a Rust wrapper for <b>Libtorch</b>. For this reason, I
    do not consider this project particularly complex but it was a good exercise
    in working with <b>Rust</b> and <b>Libtorch</b>.
  </p>

  <h2 class="left-bar fade-in">technical_details</h2>
  <p class="left-bar fade-in">
    The main concept that makes this project work is the comparison of <b
      >Cosine Similarity</b
    >
    values between the various image embeddings generated by the <b>ResNet</b> model.
    Following that, a heuristic clustering algorithm is used to group the images
    into a specified number of classes. There is more detail in the project repository
    if you are interested in the specifics.
  </p>

  <h2 class="left-bar fade-in">images</h2>
  <p class="left-bar">
    Below are images that demonstrate the usage of this tool.
  </p>
  <div class="image-container">
    <img
      class="fade-in"
      src="/images/tensort/1.png"
      alt="tensort - all images"
    />
    <img
      class="fade-in"
      src="/images/tensort/2.png"
      alt="tensort command help"
    />
    <img
      class="fade-in"
      src="/images/tensort/3.png"
      alt="tensort test run and sorting"
    />
    <img
      class="fade-in"
      src="/images/tensort/4.png"
      alt="tensort sample sorted images"
    />
  </div>
</ProjectPage>
